development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: platypusx_dev
  encoding: UTF8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: platypusx_test
  encoding: UTF8
  pool: 5
  timeout: 5000

  production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: platypusx_production
  encoding: UTF8
  pool: 5
  timeout: 5000